// SPDX-FileCopyrightText: 2023 Brian Calhoun <brian@bemorehuman.org>
//
// SPDX-License-Identifier: MIT
//
// MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
// This file is part of bemorehuman. See https://bemorehuman.org

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: recgen.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "recgen.pb-c.h"
void   internal_single_rec__init
                     (InternalSingleRec         *message)
{
  static const InternalSingleRec init_value = INTERNAL_SINGLE_REC__INIT;
  *message = init_value;
}
size_t internal_single_rec__get_packed_size
                     (const InternalSingleRec *message)
{
  assert(message->base.descriptor == &internal_single_rec__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t internal_single_rec__pack
                     (const InternalSingleRec *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &internal_single_rec__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t internal_single_rec__pack_to_buffer
                     (const InternalSingleRec *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &internal_single_rec__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InternalSingleRec *
       internal_single_rec__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InternalSingleRec *)
     protobuf_c_message_unpack (&internal_single_rec__descriptor,
                                allocator, len, data);
}
void   internal_single_rec__free_unpacked
                     (InternalSingleRec *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &internal_single_rec__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   internal_single_rec_response__init
                     (InternalSingleRecResponse         *message)
{
  static const InternalSingleRecResponse init_value = INTERNAL_SINGLE_REC_RESPONSE__INIT;
  *message = init_value;
}
size_t internal_single_rec_response__get_packed_size
                     (const InternalSingleRecResponse *message)
{
  assert(message->base.descriptor == &internal_single_rec_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t internal_single_rec_response__pack
                     (const InternalSingleRecResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &internal_single_rec_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t internal_single_rec_response__pack_to_buffer
                     (const InternalSingleRecResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &internal_single_rec_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InternalSingleRecResponse *
       internal_single_rec_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InternalSingleRecResponse *)
     protobuf_c_message_unpack (&internal_single_rec_response__descriptor,
                                allocator, len, data);
}
void   internal_single_rec_response__free_unpacked
                     (InternalSingleRecResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &internal_single_rec_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   recs__init
                     (Recs         *message)
{
  static const Recs init_value = RECS__INIT;
  *message = init_value;
}
size_t recs__get_packed_size
                     (const Recs *message)
{
  assert(message->base.descriptor == &recs__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t recs__pack
                     (const Recs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &recs__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t recs__pack_to_buffer
                     (const Recs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &recs__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Recs *
       recs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Recs *)
     protobuf_c_message_unpack (&recs__descriptor,
                                allocator, len, data);
}
void   recs__free_unpacked
                     (Recs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &recs__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rec_item__init
                     (RecItem         *message)
{
  static const RecItem init_value = REC_ITEM__INIT;
  *message = init_value;
}
size_t rec_item__get_packed_size
                     (const RecItem *message)
{
  assert(message->base.descriptor == &rec_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rec_item__pack
                     (const RecItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rec_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rec_item__pack_to_buffer
                     (const RecItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rec_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RecItem *
       rec_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RecItem *)
     protobuf_c_message_unpack (&rec_item__descriptor,
                                allocator, len, data);
}
void   rec_item__free_unpacked
                     (RecItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rec_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rating_item__init
                     (RatingItem         *message)
{
  static const RatingItem init_value = RATING_ITEM__INIT;
  *message = init_value;
}
size_t rating_item__get_packed_size
                     (const RatingItem *message)
{
  assert(message->base.descriptor == &rating_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rating_item__pack
                     (const RatingItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rating_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rating_item__pack_to_buffer
                     (const RatingItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rating_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RatingItem *
       rating_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RatingItem *)
     protobuf_c_message_unpack (&rating_item__descriptor,
                                allocator, len, data);
}
void   rating_item__free_unpacked
                     (RatingItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rating_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   recs_response__init
                     (RecsResponse         *message)
{
  static const RecsResponse init_value = RECS_RESPONSE__INIT;
  *message = init_value;
}
size_t recs_response__get_packed_size
                     (const RecsResponse *message)
{
  assert(message->base.descriptor == &recs_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t recs_response__pack
                     (const RecsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &recs_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t recs_response__pack_to_buffer
                     (const RecsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &recs_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RecsResponse *
       recs_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RecsResponse *)
     protobuf_c_message_unpack (&recs_response__descriptor,
                                allocator, len, data);
}
void   recs_response__free_unpacked
                     (RecsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &recs_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   event__init
                     (Event         *message)
{
  static const Event init_value = EVENT__INIT;
  *message = init_value;
}
size_t event__get_packed_size
                     (const Event *message)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t event__pack
                     (const Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t event__pack_to_buffer
                     (const Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Event *
       event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Event *)
     protobuf_c_message_unpack (&event__descriptor,
                                allocator, len, data);
}
void   event__free_unpacked
                     (Event *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   event_response__init
                     (EventResponse         *message)
{
  static const EventResponse init_value = EVENT_RESPONSE__INIT;
  *message = init_value;
}
size_t event_response__get_packed_size
                     (const EventResponse *message)
{
  assert(message->base.descriptor == &event_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t event_response__pack
                     (const EventResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &event_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t event_response__pack_to_buffer
                     (const EventResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &event_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EventResponse *
       event_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EventResponse *)
     protobuf_c_message_unpack (&event_response__descriptor,
                                allocator, len, data);
}
void   event_response__free_unpacked
                     (EventResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &event_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor internal_single_rec__field_descriptors[2] =
{
  {
    "personid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(InternalSingleRec, personid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elementid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(InternalSingleRec, elementid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned internal_single_rec__field_indices_by_name[] = {
  1,   /* field[1] = elementid */
  0,   /* field[0] = personid */
};
static const ProtobufCIntRange internal_single_rec__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor internal_single_rec__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InternalSingleRec",
  "InternalSingleRec",
  "InternalSingleRec",
  "",
  sizeof(InternalSingleRec),
  2,
  internal_single_rec__field_descriptors,
  internal_single_rec__field_indices_by_name,
  1,  internal_single_rec__number_ranges,
  (ProtobufCMessageInit) internal_single_rec__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor internal_single_rec_response__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(InternalSingleRecResponse, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(InternalSingleRecResponse, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned internal_single_rec_response__field_indices_by_name[] = {
  0,   /* field[0] = result */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange internal_single_rec_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor internal_single_rec_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InternalSingleRecResponse",
  "InternalSingleRecResponse",
  "InternalSingleRecResponse",
  "",
  sizeof(InternalSingleRecResponse),
  2,
  internal_single_rec_response__field_descriptors,
  internal_single_rec_response__field_indices_by_name,
  1,  internal_single_rec_response__number_ranges,
  (ProtobufCMessageInit) internal_single_rec_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor recs__field_descriptors[4] =
{
  {
    "personid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Recs, personid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "popularity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Recs, popularity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numratings",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Recs, numratings),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ratingslist",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Recs, n_ratingslist),
    offsetof(Recs, ratingslist),
    &rating_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned recs__field_indices_by_name[] = {
  2,   /* field[2] = numratings */
  0,   /* field[0] = personid */
  1,   /* field[1] = popularity */
  3,   /* field[3] = ratingslist */
};
static const ProtobufCIntRange recs__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor recs__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Recs",
  "Recs",
  "Recs",
  "",
  sizeof(Recs),
  4,
  recs__field_descriptors,
  recs__field_indices_by_name,
  1,  recs__number_ranges,
  (ProtobufCMessageInit) recs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rec_item__field_descriptors[3] =
{
  {
    "elementid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RecItem, elementid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rating",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RecItem, rating),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "popularity",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RecItem, popularity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rec_item__field_indices_by_name[] = {
  0,   /* field[0] = elementid */
  2,   /* field[2] = popularity */
  1,   /* field[1] = rating */
};
static const ProtobufCIntRange rec_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rec_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RecItem",
  "RecItem",
  "RecItem",
  "",
  sizeof(RecItem),
  3,
  rec_item__field_descriptors,
  rec_item__field_indices_by_name,
  1,  rec_item__number_ranges,
  (ProtobufCMessageInit) rec_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rating_item__field_descriptors[2] =
{
  {
    "elementid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RatingItem, elementid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rating",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RatingItem, rating),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rating_item__field_indices_by_name[] = {
  0,   /* field[0] = elementid */
  1,   /* field[1] = rating */
};
static const ProtobufCIntRange rating_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rating_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RatingItem",
  "RatingItem",
  "RatingItem",
  "",
  sizeof(RatingItem),
  2,
  rating_item__field_descriptors,
  rating_item__field_indices_by_name,
  1,  rating_item__number_ranges,
  (ProtobufCMessageInit) rating_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor recs_response__field_descriptors[2] =
{
  {
    "recslist",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RecsResponse, n_recslist),
    offsetof(RecsResponse, recslist),
    &rec_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RecsResponse, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned recs_response__field_indices_by_name[] = {
  0,   /* field[0] = recslist */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange recs_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor recs_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RecsResponse",
  "RecsResponse",
  "RecsResponse",
  "",
  sizeof(RecsResponse),
  2,
  recs_response__field_descriptors,
  recs_response__field_indices_by_name,
  1,  recs_response__number_ranges,
  (ProtobufCMessageInit) recs_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor event__field_descriptors[3] =
{
  {
    "personid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Event, personid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elementid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Event, elementid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eventval",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Event, eventval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned event__field_indices_by_name[] = {
  1,   /* field[1] = elementid */
  2,   /* field[2] = eventval */
  0,   /* field[0] = personid */
};
static const ProtobufCIntRange event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Event",
  "Event",
  "Event",
  "",
  sizeof(Event),
  3,
  event__field_descriptors,
  event__field_indices_by_name,
  1,  event__number_ranges,
  (ProtobufCMessageInit) event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor event_response__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EventResponse, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EventResponse, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned event_response__field_indices_by_name[] = {
  0,   /* field[0] = result */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange event_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor event_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EventResponse",
  "EventResponse",
  "EventResponse",
  "",
  sizeof(EventResponse),
  2,
  event_response__field_descriptors,
  event_response__field_indices_by_name,
  1,  event_response__number_ranges,
  (ProtobufCMessageInit) event_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
